require:
  - rubocop-sequel
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: false
  DisplayStyleGuide: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.6.3

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: never

RSpec/MultipleExpectations:
  Enabled: false
