version: "3.4"
services:

  postgresql:
    container_name: "super_bank_api_v2_postgres"
    image: postgres
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super_bank_api_postgres_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgresql/data

volumes:
  pgdata:
