source 'https://rubygems.org'
ruby '3.1.2'

gem 'bcrypt'
gem 'dotenv'
gem 'dry-validation'
gem 'fast_jsonapi'
gem 'pg', '>= 0.18', '< 1.0'
gem 'pry'
gem 'puma'
gem 'rack-cors'
gem 'rack-unreloader'
gem 'rake'
gem 'roda'
gem 'rspec'
gem 'rubocop', group: 'development'
gem 'sequel'
